import type { BusinessGoal, SoftwareTool } from "./types";

export const SOFTWARE_TOOLS: SoftwareTool[] = [
  // Audio & Video
  {
    id: "descript",
    name: "Descript",
    category: "Audio Editing & Hosting",
    description:
      "AI-powered audio and video editor with automatic transcription.",
    avgMonthlyPrice: 24,
    pricingTierSummary: "$12 - $24/mo per user",
    commonIntegrations: ["podbean", "buzzsprout", "youtube", "drive"],
    capabilities: ["audio-editing", "transcription", "screen-recording"],
    websiteUrl: "https://descript.com",
    iconName: "Mic",
  },
  {
    id: "buzzsprout",
    name: "Buzzsprout",
    category: "Audio Editing & Hosting",
    description: "Podcast hosting platform with RSS feed distribution.",
    avgMonthlyPrice: 18,
    pricingTierSummary: "$12 - $24/mo",
    commonIntegrations: ["descript", "spotify", "apple-podcasts", "canva"],
    capabilities: ["podcast-hosting", "analytics", "rss-distribution"],
    websiteUrl: "https://buzzsprout.com",
    iconName: "Radio",
  },
  {
    id: "riverside",
    name: "Riverside.fm",
    category: "Video Recording & Editing",
    description: "Studio-quality remote video and audio recording platform.",
    avgMonthlyPrice: 29,
    pricingTierSummary: "$15 - $29/mo",
    commonIntegrations: ["descript", "youtube", "spotify", "buzzsprout"],
    capabilities: ["remote-recording", "multitrack-audio", "4k-video"],
    websiteUrl: "https://riverside.fm",
    iconName: "Video",
  },

  // E-Commerce & Storefront
  {
    id: "shopify",
    name: "Shopify",
    category: "E-Commerce & Storefront",
    description: "All-in-one commerce platform for online stores and POS.",
    avgMonthlyPrice: 39,
    pricingTierSummary: "$39 - $105/mo",
    commonIntegrations: [
      "stripe",
      "klaviyo",
      "shipstation",
      "zapier",
      "google-analytics",
    ],
    capabilities: [
      "storefront",
      "inventory-management",
      "checkout",
      "product-catalog",
    ],
    websiteUrl: "https://shopify.com",
    iconName: "ShoppingBag",
  },
  {
    id: "woocommerce",
    name: "WooCommerce",
    category: "E-Commerce & Storefront",
    description: "Open-source e-commerce plugin for WordPress.",
    avgMonthlyPrice: 25,
    pricingTierSummary: "Free core plugin; ~$25/mo hosting & plugins",
    commonIntegrations: ["stripe", "mailchimp", "zapier", "wordpress"],
    capabilities: ["storefront", "customization", "inventory"],
    websiteUrl: "https://woocommerce.com",
    iconName: "Store",
  },

  // Payments
  {
    id: "stripe",
    name: "Stripe",
    category: "Payment Processing",
    description:
      "Financial infrastructure for internet commerce and subscription billing.",
    avgMonthlyPrice: 0,
    pricingTierSummary: "2.9% + 30¢ per successful charge",
    commonIntegrations: [
      "shopify",
      "woocommerce",
      "hubspot",
      "xero",
      "quickbooks",
      "zapier",
    ],
    capabilities: [
      "payment-gateway",
      "subscription-billing",
      "invoicing",
      "fraud-prevention",
    ],
    websiteUrl: "https://stripe.com",
    iconName: "CreditCard",
  },
  {
    id: "paypal",
    name: "PayPal / Braintree",
    category: "Payment Processing",
    description:
      "Global digital payment gateway for web and mobile transactions.",
    avgMonthlyPrice: 0,
    pricingTierSummary: "3.49% + 49¢ per transaction",
    commonIntegrations: ["shopify", "woocommerce", "bigcommerce"],
    capabilities: ["payment-gateway", "express-checkout"],
    websiteUrl: "https://paypal.com",
    iconName: "Wallet",
  },

  // Email Marketing & Automation
  {
    id: "klaviyo",
    name: "Klaviyo",
    category: "Email Marketing & Automation",
    description:
      "E-commerce focused automated email and SMS marketing platform.",
    avgMonthlyPrice: 60,
    pricingTierSummary: "$20 - $100+/mo based on contacts",
    commonIntegrations: [
      "shopify",
      "woocommerce",
      "stripe",
      "gorgias",
      "recharge",
    ],
    capabilities: [
      "email-automation",
      "sms-marketing",
      "segmentation",
      "analytics",
    ],
    websiteUrl: "https://klaviyo.com",
    iconName: "Mail",
  },
  {
    id: "convertkit",
    name: "Kit (ConvertKit)",
    category: "Email Marketing & Automation",
    description:
      "Email marketing platform designed for creators, podcasters, and authors.",
    avgMonthlyPrice: 29,
    pricingTierSummary: "$15 - $50/mo",
    commonIntegrations: [
      "buzzsprout",
      "teachable",
      "gumroad",
      "stripe",
      "zapier",
    ],
    capabilities: ["email-broadcasts", "landing-pages", "visual-automations"],
    websiteUrl: "https://kit.com",
    iconName: "Send",
  },
  {
    id: "mailchimp",
    name: "Mailchimp",
    category: "Email Marketing & Automation",
    description:
      "Popular email marketing, newsletter, and marketing automation tool.",
    avgMonthlyPrice: 35,
    pricingTierSummary: "$20 - $60/mo",
    commonIntegrations: [
      "shopify",
      "woocommerce",
      "canva",
      "wordpress",
      "zapier",
    ],
    capabilities: ["email-campaigns", "audience-insights", "templates"],
    websiteUrl: "https://mailchimp.com",
    iconName: "Inbox",
  },

  // CRM & Pipeline
  {
    id: "hubspot",
    name: "HubSpot CRM",
    category: "CRM & Lead Pipeline",
    description:
      "Inbound CRM, sales pipeline, marketing automation, and customer platform.",
    avgMonthlyPrice: 50,
    pricingTierSummary: "Free tier available; $50 - $500+/mo",
    commonIntegrations: [
      "stripe",
      "zapier",
      "slack",
      "gmail",
      "typeform",
      "intercom",
    ],
    capabilities: [
      "crm-pipeline",
      "lead-tracking",
      "email-logging",
      "deal-stages",
    ],
    websiteUrl: "https://hubspot.com",
    iconName: "Users",
  },
  {
    id: "pipedrive",
    name: "Pipedrive",
    category: "CRM & Lead Pipeline",
    description:
      "Sales-focused CRM tool designed by salespeople for sales teams.",
    avgMonthlyPrice: 28,
    pricingTierSummary: "$14 - $49/mo per user",
    commonIntegrations: ["zapier", "slack", "google-workspace", "outreach"],
    capabilities: ["sales-pipeline", "activity-tracking", "call-logging"],
    websiteUrl: "https://pipedrive.com",
    iconName: "Target",
  },
  {
    id: "salesforce",
    name: "Salesforce Sales Cloud",
    category: "CRM & Lead Pipeline",
    description: "Enterprise CRM platform for end-to-end sales management.",
    avgMonthlyPrice: 150,
    pricingTierSummary: "$25 - $300/mo per user",
    commonIntegrations: ["slack", "hubspot", "jira", "stripe", "zapier"],
    capabilities: ["enterprise-crm", "lead-scoring", "opportunity-tracking"],
    websiteUrl: "https://salesforce.com",
    iconName: "Briefcase",
  },

  // Project Management
  {
    id: "asana",
    name: "Asana",
    category: "Project Management",
    description: "Work management and project tracking software for teams.",
    avgMonthlyPrice: 25,
    pricingTierSummary: "$10.99 - $24.99/mo per user",
    commonIntegrations: ["slack", "google-drive", "jira", "zapier", "github"],
    capabilities: ["task-tracking", "kanban-boards", "project-timelines"],
    websiteUrl: "https://asana.com",
    iconName: "CheckSquare",
  },
  {
    id: "monday",
    name: "Monday.com",
    category: "Project Management",
    description:
      "Customizable Work OS for project planning and team collaboration.",
    avgMonthlyPrice: 30,
    pricingTierSummary: "$12 - $30/mo per user",
    commonIntegrations: ["slack", "hubspot", "jira", "zapier", "gmail"],
    capabilities: ["work-management", "automation", "dashboards"],
    websiteUrl: "https://monday.com",
    iconName: "Layout",
  },
  {
    id: "clickup",
    name: "ClickUp",
    category: "Project Management",
    description:
      "All-in-one productivity platform for tasks, docs, goals, and chat.",
    avgMonthlyPrice: 19,
    pricingTierSummary: "$7 - $19/mo per user",
    commonIntegrations: ["slack", "github", "google-drive", "zapier", "figma"],
    capabilities: ["task-management", "docs", "time-tracking"],
    websiteUrl: "https://clickup.com",
    iconName: "Layers",
  },
  {
    id: "notion",
    name: "Notion",
    category: "Project Management",
    description:
      "Connected workspace for wiki, docs, notes, and task management.",
    avgMonthlyPrice: 10,
    pricingTierSummary: "$8 - $15/mo per user",
    commonIntegrations: ["slack", "github", "figma", "zapier"],
    capabilities: ["knowledge-base", "docs", "light-crm", "database"],
    websiteUrl: "https://notion.so",
    iconName: "FileText",
  },

  // Customer Support
  {
    id: "gorgias",
    name: "Gorgias",
    category: "Customer Support & Helpdesk",
    description:
      "E-commerce customer service desk integrated with Shopify & Klaviyo.",
    avgMonthlyPrice: 60,
    pricingTierSummary: "$10 - $60+/mo",
    commonIntegrations: ["shopify", "klaviyo", "recharge", "shipstation"],
    capabilities: ["ecom-helpdesk", "ticket-management", "live-chat"],
    websiteUrl: "https://gorgias.com",
    iconName: "HelpCircle",
  },
  {
    id: "intercom",
    name: "Intercom",
    category: "Customer Support & Helpdesk",
    description:
      "AI-first customer service platform, live chat, and help center.",
    avgMonthlyPrice: 74,
    pricingTierSummary: "$39 - $99/mo per seat",
    commonIntegrations: ["hubspot", "stripe", "jira", "slack", "zapier"],
    capabilities: ["ai-chat", "helpdesk", "product-tours"],
    websiteUrl: "https://intercom.com",
    iconName: "MessageSquare",
  },
  {
    id: "zendesk",
    name: "Zendesk",
    category: "Customer Support & Helpdesk",
    description: "Complete omnichannel customer service and ticketing system.",
    avgMonthlyPrice: 55,
    pricingTierSummary: "$19 - $115/mo per agent",
    commonIntegrations: ["jira", "shopify", "salesforce", "slack"],
    capabilities: ["ticketing-system", "knowledge-base", "call-center"],
    websiteUrl: "https://zendesk.com",
    iconName: "Headphones",
  },

  // Analytics & BI
  {
    id: "google-analytics",
    name: "Google Analytics 4",
    category: "Analytics & Business Intelligence",
    description: "Web and app measurement platform for user behavior tracking.",
    avgMonthlyPrice: 0,
    pricingTierSummary: "Free (GA4 standard)",
    commonIntegrations: ["shopify", "woocommerce", "hubspot", "google-ads"],
    capabilities: ["web-analytics", "event-tracking", "conversion-funnels"],
    websiteUrl: "https://analytics.google.com",
    iconName: "BarChart",
  },
  {
    id: "mixpanel",
    name: "Mixpanel",
    category: "Analytics & Business Intelligence",
    description:
      "Product analytics tool for mobile and web application behavior.",
    avgMonthlyPrice: 28,
    pricingTierSummary: "Free tier; $28 - $80/mo",
    commonIntegrations: ["stripe", "segment", "intercom", "hubspot"],
    capabilities: ["product-analytics", "retention-cohorts", "funnel-analysis"],
    websiteUrl: "https://mixpanel.com",
    iconName: "PieChart",
  },

  // Design & Media
  {
    id: "canva",
    name: "Canva Pro",
    category: "Design & Media Assets",
    description: "Online visual design and content creation platform.",
    avgMonthlyPrice: 15,
    pricingTierSummary: "$12.99 - $15/mo",
    commonIntegrations: ["mailchimp", "buzzsprout", "shopify", "social-media"],
    capabilities: ["social-graphics", "brand-kit", "banner-design"],
    websiteUrl: "https://canva.com",
    iconName: "Image",
  },
  {
    id: "figma",
    name: "Figma",
    category: "Design & Media Assets",
    description: "Collaborative interface design and prototyping tool.",
    avgMonthlyPrice: 15,
    pricingTierSummary: "$12 - $45/mo per editor",
    commonIntegrations: ["notion", "slack", "jira", "clickup"],
    capabilities: ["ui-ux-design", "prototyping", "design-system"],
    websiteUrl: "https://figma.com",
    iconName: "Figma",
  },

  // Form Builders
  {
    id: "typeform",
    name: "Typeform",
    category: "Form Builder & Data Collection",
    description:
      "Interactive forms, surveys, and quiz builder with high response rates.",
    avgMonthlyPrice: 25,
    pricingTierSummary: "$25 - $83/mo",
    commonIntegrations: ["hubspot", "zapier", "slack", "notion", "stripe"],
    capabilities: ["conversational-forms", "surveys", "lead-capture"],
    websiteUrl: "https://typeform.com",
    iconName: "ListChecks",
  },
  {
    id: "tally",
    name: "Tally Forms",
    category: "Form Builder & Data Collection",
    description:
      "Simple, powerful form builder that works like a Notion document.",
    avgMonthlyPrice: 0,
    pricingTierSummary: "99% Free; $29/mo Pro",
    commonIntegrations: ["notion", "zapier", "webhooks", "airtable"],
    capabilities: ["notion-like-forms", "payment-forms", "logic-jump"],
    websiteUrl: "https://tally.so",
    iconName: "FormInput",
  },

  // Automation / iPaaS
  {
    id: "zapier",
    name: "Zapier",
    category: "Workflow Automation & iPaaS",
    description:
      "No-code workflow automation connecting 7,000+ web applications.",
    avgMonthlyPrice: 30,
    pricingTierSummary: "Free tier; $20 - $75/mo",
    commonIntegrations: [
      "hubspot",
      "shopify",
      "slack",
      "stripe",
      "notion",
      "typeform",
    ],
    capabilities: ["no-code-zaps", "multi-step-automation", "webhooks"],
    websiteUrl: "https://zapier.com",
    iconName: "Zap",
  },
  {
    id: "make",
    name: "Make (Integromat)",
    category: "Workflow Automation & iPaaS",
    description:
      "Visual automation platform for building complex data workflows.",
    avgMonthlyPrice: 16,
    pricingTierSummary: "Free tier; $9 - $29/mo",
    commonIntegrations: [
      "airtable",
      "stripe",
      "notion",
      "shopify",
      "google-sheets",
    ],
    capabilities: ["visual-scenario-builder", "data-mapping", "webhooks"],
    websiteUrl: "https://make.com",
    iconName: "Cpu",
  },
];

export const GOAL_TEMPLATES: BusinessGoal[] = [
  {
    id: "podcast-launch",
    name: "Launch & Distribute a Podcast",
    category: "Media & Content",
    description:
      "Record remote guests, edit audio with AI transcription, host RSS feeds, and automate audience email distribution.",
    iconName: "Mic",
    estimatedTotalMonthlyCost: 86,
    stepTemplates: [
      {
        stepNumber: 1,
        title: "Remote Audio/Video Recording",
        description:
          "Capture high-fidelity studio recording with remote guests.",
        preferredCategory: "Video Recording & Editing",
        defaultToolId: "riverside",
        alternativeToolIds: ["descript"],
      },
      {
        stepNumber: 2,
        title: "Audio Editing & Transcription",
        description:
          "Edit audio, remove filler words, and generate show notes.",
        preferredCategory: "Audio Editing & Hosting",
        defaultToolId: "descript",
        alternativeToolIds: ["canva"],
      },
      {
        stepNumber: 3,
        title: "Podcast Hosting & RSS Distribution",
        description:
          "Host audio files and distribute to Spotify, Apple Podcasts.",
        preferredCategory: "Audio Editing & Hosting",
        defaultToolId: "buzzsprout",
        alternativeToolIds: ["descript"],
      },
      {
        stepNumber: 4,
        title: "Listener Newsletter & Audience Automation",
        description:
          "Build subscriber list and send automated episode updates.",
        preferredCategory: "Email Marketing & Automation",
        defaultToolId: "convertkit",
        alternativeToolIds: ["mailchimp", "klaviyo"],
      },
      {
        stepNumber: 5,
        title: "Cover Art & Social Promo Assets",
        description:
          "Design episode banners, video snippets, and social graphics.",
        preferredCategory: "Design & Media Assets",
        defaultToolId: "canva",
        alternativeToolIds: ["figma"],
      },
    ],
  },
  {
    id: "e-commerce-store",
    name: "Start an Online Store & Retail Brand",
    category: "E-Commerce",
    description:
      "Set up e-commerce storefront, process secure payments, automate order email flows, and handle customer support.",
    iconName: "ShoppingBag",
    estimatedTotalMonthlyCost: 198,
    stepTemplates: [
      {
        stepNumber: 1,
        title: "Storefront & Inventory Catalog",
        description: "Host online store, manage checkout, and list products.",
        preferredCategory: "E-Commerce & Storefront",
        defaultToolId: "shopify",
        alternativeToolIds: ["woocommerce"],
      },
      {
        stepNumber: 2,
        title: "Payment Processing & Merchant Gateway",
        description: "Accept credit cards, Apple Pay, and local currencies.",
        preferredCategory: "Payment Processing",
        defaultToolId: "stripe",
        alternativeToolIds: ["paypal"],
      },
      {
        stepNumber: 3,
        title: "Customer & Abandoned Cart Email Flows",
        description:
          "Send automated receipt emails and recover abandoned checkouts.",
        preferredCategory: "Email Marketing & Automation",
        defaultToolId: "klaviyo",
        alternativeToolIds: ["mailchimp"],
      },
      {
        stepNumber: 4,
        title: "Helpdesk & Customer Order Support",
        description:
          "Manage shipping queries, order status, and customer tickets.",
        preferredCategory: "Customer Support & Helpdesk",
        defaultToolId: "gorgias",
        alternativeToolIds: ["intercom", "zendesk"],
      },
      {
        stepNumber: 5,
        title: "Store Analytics & Conversion Funnels",
        description: "Track traffic, sales attribution, and conversion rates.",
        preferredCategory: "Analytics & Business Intelligence",
        defaultToolId: "google-analytics",
        alternativeToolIds: ["mixpanel"],
      },
    ],
  },
  {
    id: "b2b-sales-pipeline",
    name: "B2B Sales Pipeline & Lead Capture",
    category: "Sales & Operations",
    description:
      "Capture inbound qualified leads, track pipeline stages in CRM, schedule discovery calls, and manage client tasks.",
    iconName: "Target",
    estimatedTotalMonthlyCost: 134,
    stepTemplates: [
      {
        stepNumber: 1,
        title: "Lead Qualification & Inbound Form",
        description:
          "Collect project scope and budget details from site visitors.",
        preferredCategory: "Form Builder & Data Collection",
        defaultToolId: "typeform",
        alternativeToolIds: ["tally"],
      },
      {
        stepNumber: 2,
        title: "Sales Pipeline & CRM Deal Stages",
        description:
          "Organize prospects, log deal stages, and track revenue forecasts.",
        preferredCategory: "CRM & Lead Pipeline",
        defaultToolId: "hubspot",
        alternativeToolIds: ["pipedrive", "salesforce"],
      },
      {
        stepNumber: 3,
        title: "Lead Sync & Automation Integration",
        description: "Connect form submissions instantly to CRM deal creation.",
        preferredCategory: "Workflow Automation & iPaaS",
        defaultToolId: "zapier",
        alternativeToolIds: ["make"],
      },
      {
        stepNumber: 4,
        title: "Client Onboarding & Project Management",
        description: "Track project deliverables, tasks, and client timelines.",
        preferredCategory: "Project Management",
        defaultToolId: "asana",
        alternativeToolIds: ["monday", "notion", "clickup"],
      },
    ],
  },
  {
    id: "content-creator-ecosystem",
    name: "Content Creator & Digital Product Hub",
    category: "Creator Economy",
    description:
      "Build an audience, distribute newsletters, sell digital goods, and manage content calendars.",
    iconName: "Sparkles",
    estimatedTotalMonthlyCost: 84,
    stepTemplates: [
      {
        stepNumber: 1,
        title: "Audience Newsletter & Email List",
        description:
          "Publish subscriber newsletters and build custom landing pages.",
        preferredCategory: "Email Marketing & Automation",
        defaultToolId: "convertkit",
        alternativeToolIds: ["mailchimp"],
      },
      {
        stepNumber: 2,
        title: "Content Calendar & Knowledge Wiki",
        description:
          "Draft posts, store research notes, and schedule publication.",
        preferredCategory: "Project Management",
        defaultToolId: "notion",
        alternativeToolIds: ["asana", "clickup"],
      },
      {
        stepNumber: 3,
        title: "Digital Product Checkout & Billing",
        description:
          "Process payments for ebooks, courses, or digital templates.",
        preferredCategory: "Payment Processing",
        defaultToolId: "stripe",
        alternativeToolIds: ["paypal"],
      },
      {
        stepNumber: 4,
        title: "Visual Assets & Thumbnail Design",
        description:
          "Design YouTube thumbnails, PDF covers, and social graphics.",
        preferredCategory: "Design & Media Assets",
        defaultToolId: "canva",
        alternativeToolIds: ["figma"],
      },
    ],
  },
];
